name: Build and Test
description: 'Build and test the dog-registration service'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download
        working-directory: ./dog-registration

      - name: Run tests
        run: go test -v ./...
        working-directory: ./dog-registration

