name: CI-2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dog-register:
    runs-on: ubuntu-latest
    steps:
      - name: call-build-test
        uses: ./.github/workflows/build_test.yml
      - name: call-performance-test
        uses: ./.github/workflows/performance_test.yml
