name: CI-2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-test:
    name: 'Unit Test dog-registration'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build_test.yml
  
  run-services:
    name: 'Run Services'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

  call-performace-test:
    name: 'Performance Test dog-registration'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/performance_test.yml
