name: CI-2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-test:
    uses: gunesmes/dog-app/dog-registration/.github/workflows/build_test.yml@main
  call-performance-test:
    uses: gunesmes/dog-app/dog-registration/.github/workflows/performance_test.yml@main
